export default ActionTypes = {
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    LOADING: "LOADING",
    LOGIN_ERROR: "LOGIN_ERROR",
    CONNECTION_ERROR: "CONNECTION_ERROR",
    CLEAR_MESSAGES: "CLEAR_MESSAGES",
    SIGNUP_ERROR: "SIGNUP_ERROR",
}