export default ActionTypes = {
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    LOGOUT: "LOGOUT",
    LOADING: "LOADING",
    MESSAGE: "MESSAGE",
    CONNECTION_ERROR: "CONNECTION_ERROR",
    CLEAR_MESSAGES: "CLEAR_MESSAGES",
    SIGNUP_ERROR: "SIGNUP_ERROR",
    GET_WEIGHTS: "GET_WEIGHTS",
    ADD_WEIGHT: "ADD_WEIGHT",
}