export const strings = {
    USERNAME_PLACEHOLDER: "Username",
    PASSWORD_PLACEHOLDER: "Password",
    CONFIRM_PASSWORD_PLACEHOLDER: "Confirm password",
    ADD_WEIGHT_PLACEHOLDER: 'Weight',
    LOGIN: "LOGIN",
    SIGNUP: "SIGN UP",
    LOGOUT: "LOGOUT",
    SIGNUP_SUCCESS: "Your account has been created. You may log in now",
    CREATE_NEW_ACCOUNT: "Create new account",
    CONNECTION_ERROR_MESSAGE: "Connection error. Check your internet connection",
    LOGIN_SUCCESS: "Logged in",
    SIGNUP_SUCCESS: "Account created. You can log in now",
    PASSWORDS_DONT_MATCH_ERROR: "Passwords don't match",
    ADD_WEIGHT_SUCCESS: "Weight added successfully",
    EDIT_WEIGHT_SUCCESS: "Weight changed succesfully",
    DELETE_WEIGHT_SUCCESS: "Weight deleted succesfully",
}